import Head from 'next/head'
import Image from 'next/image'
import SectionBanner from '../components/home/SectionBanner'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Cosmohub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <SectionBanner />
      </main>

      <footer>
      
      </footer>
    </div>
  )
}
